name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Generate Gradle Wrapper if missing
      run: |
        if [ ! -f ./gradlew ]; then
          echo "No gradlew found, generating with system gradle..."
          gradle wrapper
        fi

    - name: Build with Gradle
      run: ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: voice-ai-app
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Install rar
      run: sudo apt-get update && sudo apt-get install -y rar

    - name: RAR Split APK
      run: |
        APK_PATH="app/build/outputs/apk/debug/app-debug.apk"
        if [ -f "$APK_PATH" ]; then
          rar a -v7900k "$APK_PATH.rar" "$APK_PATH"
        else
          echo "APK 文件不存在，无法压缩。"
        fi

    - name: Upload RAR parts to Discord Webhook
      if: always()
      run: |
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        for part in app/build/outputs/apk/debug/app-debug.apk.rar*; do
          if [ -f "$part" ]; then
            curl -F "file=@$part" \
                 -F "payload_json={\"content\": \"RAR分卷: $(basename $part)\"}" \
                 "$DISCORD_WEBHOOK_URL"
          fi
        done