name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Generate Gradle Wrapper if missing
      run: |
        if [ ! -f ./gradlew ]; then
          echo "No gradlew found, generating with system gradle..."
          gradle wrapper
        fi

    - name: Build with Gradle
      run: ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: voice-ai-app
        path: app/build/outputs/apk/debug/app-debug.apk