name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Generate Gradle Wrapper if missing
      run: |
        if [ ! -f ./gradlew ]; then
          echo "No gradlew found, generating with system gradle..."
          gradle wrapper
        fi

    - name: Build with Gradle
      run: ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: voice-ai-app
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Install rar
      run: |
        wget -O rarlinux-x64.tar.gz https://www.rarlab.com/rar/rarlinux-x64-623.tar.gz
        tar -xzvf rarlinux-x64.tar.gz
        sudo cp rar/rar rar/unrar /usr/bin/

    - name: RAR Split APK
      run: |
        APK_PATH="app/build/outputs/apk/debug/app-debug.apk"
        if [ -f "$APK_PATH" ]; then
          rar a -ep1 -htb -m0 -ma5 -rr5 -ts -tsp -v8274094B "$APK_PATH.rar" "$APK_PATH"
        else
          echo "APK 文件不存在，无法压缩。"
        fi

    - name: Upload RAR parts to Discord Webhook
      if: always()
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        for part in app/build/outputs/apk/debug/app-debug.apk.rar*; do
          if [ -f "$part" ]; then
            curl -F "file=@$part" \
                 -F "payload_json={\"content\": \"RAR分卷: $(basename $part)\"}" \
                 "${{ secrets.DISCORD_WEBHOOK_URL }}"
          fi
        done

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c

    - name: Clone whisper.cpp
      run: git clone --depth 1 https://github.com/ggerganov/whisper.cpp.git

    - name: Build libwhisper.so for arm64-v8a
      run: |
        cd whisper.cpp
        mkdir -p build-android && cd build-android
        cmake .. -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 -DBUILD_SHARED_LIBS=ON
        make -j$(nproc)
        mkdir -p ../../app/src/main/jniLibs/arm64-v8a/
        cp libwhisper.so ../../app/src/main/jniLibs/arm64-v8a/

    - name: Download Whisper model
      run: |
        mkdir -p app/src/main/assets
        wget -O app/src/main/assets/ggml-base.en.bin https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin